language: minimal
addons:
  apt:
    update: true
    packages:
      - graphviz
jobs:
  include:
    - stage: diagrams
      script:
        - neato -Tsvg -OER ER.dot
        - cp *.svg pages
deploy:
  provider: pages
  local-dir: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master