language: minimal
dist: xenial
addons:
  apt:
    update: true
    packages:
      - graphviz
      - wget
      - openjdk-8-jre
      - pandoc
before_script:
  - wget http://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar
script:
  - java -jar plantuml.jar -tsvg Phase1/UML.plantuml
  - ls && echo "" && ls Phase1
  - mv Phase1/PokemonDB.svg pages/PokemonDB.svg
  - sed -i /\<\!--Description--\>/r/<(pandoc -t html Phase1\/Description.md) pages/index.html
  - sed -i /\<\!--Schemas--\>/r/<(pandoc -t html Phase1\/Schemas.md) pages/index.html
deploy:
  provider: pages
  local-dir: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
