version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |-
            apt-get update
            apt-get install -y graphviz

      - run:
          name: Compile Diagrams
          command: neato -Tsvg -OER ER.dot