# Generated by Django 2.2 on 2019-05-07 19:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemonappearance',
            name='game',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='attack',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attack',
            name='power',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attack',
            name='pp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attack',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='media',
            name='data',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='media',
            name='of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='gender_distribution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='legendary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pokemonappearance',
            name='base_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemonappearance',
            name='base_defence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemonappearance',
            name='base_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemonappearance',
            name='base_sp_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemonappearance',
            name='base_sp_defence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemonappearance',
            name='base_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemoncanlearn',
            name='at_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typematchup',
            name='effectiveness_multiplier',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Pokemon')),
                ('pokemon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Type')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Pokemon')),
                ('pokemon_ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Ability')),
            ],
        ),
    ]
