# Generated by Django 2.2 on 2019-05-03 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_height-weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Pokemon'),
        ),
    ]
