# Generated by Django 2.2 on 2019-05-03 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_media-cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attack',
            name='power',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attack',
            name='pp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attack',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='media',
            name='data',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='gender_distribution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='legendary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemonappearance',
            name='base_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemonappearance',
            name='base_defence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemonappearance',
            name='base_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemonappearance',
            name='base_sp_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemonappearance',
            name='base_sp_defence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemonappearance',
            name='base_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemoncanlearn',
            name='at_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typematchup',
            name='effectiveness_multiplier',
            field=models.FloatField(default=0),
        ),
    ]
