# Generated by Django 2.2 on 2019-05-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_enable-getorcreate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonappearance',
            name='game',
        ),
    ]
