# Generated by Django 2.2.1 on 2019-05-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_abilities_pokemonabilities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abilities',
            new_name='Abilitie',
        ),
        migrations.RenameModel(
            old_name='PokemonAbilities',
            new_name='PokemonAbilitie',
        ),
    ]
