# Generated by Django 2.2.1 on 2019-05-04 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20190504_0524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abilitie',
            new_name='Ability',
        ),
        migrations.RenameModel(
            old_name='PokemonAbilitie',
            new_name='PokemonAbility',
        ),
    ]
