# Generated by Django 2.2.1 on 2019-05-05 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20190505_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='defence',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='sp_attack',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='sp_defence',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='speed',
        ),
        migrations.CreateModel(
            name='PokemonStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Pokemon')),
                ('pokemon_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Stat')),
            ],
        ),
    ]
