# Generated by Django 2.2.1 on 2019-05-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20190505_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonstat',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
