# Generated by Django 2.2.1 on 2019-05-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_pokemonstat_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonappearance',
            name='game',
        ),
    ]
