# Generated by Django 2.2 on 2019-05-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_remove_pokemonappearance_game'),
        ('frontend', '0006_remove_pokemonappearance_game'),
    ]

    operations = [
    ]
